server:
  port: 7466

spring:
  application:
    name: seckill-web-API
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=GMT%2b8&characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.0.1:3306/seckill?serverTimezone=GMT%2b8
#    username: root
#    password: admin
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 1
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1