server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
    leaseExpirationDurationInSeconds: 6
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    enableSelfPreservation: false
    responseCacheUpdateIntervalMs: 3000
    evictionIntervalTimerInMs: 6000